# Generated by Django 2.2 on 2025-02-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_likes_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
