# Generated by Django 2.2 on 2025-02-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20250206_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Views',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
